django-hijack/django-hijack

hijack/helpers.py

Hello,
This patch just adds the ability for a user to pass in a ```next``` GET parameter to adjust the redirect before attempts are made at the ```LOGIN_REDIRECT_URL```.
Thanks!

Add ability to specify the redirect that occurs after a hijack or release

---

hijack/tests/test_settings.py
hijack/urls.py

The reason for this is the same as arteria/django-hijack#43 , to minimize extra URLs when a settings is not enabled.

Only include 'disable-hijack-warning' url if HIJACK_NOTIFY_ADMIN is enabled

---

hijack/helpers.py

The code gave permission denied if the current user had staff status as this code
checks against the user that is being hijacked instead of the user hijacking.

Check staff status against logged in user instead the user being hijacked

---

hijack/helpers.py
hijack/tests/hijack_tests.py

This adds a check when staff users are hijacking to see if the users that is being hijacked is a superuser. If that is the case the request is denied. This also adds some additional tests that should pass.

Do not allow staff users to hijack superusers

---

README.md
hijack/admin.py
hijack/urls.py

This adds a ALLOWED_HIJACKING_USER_ATTRIBUTES settings allowing developers to specify which user attributes can be used when hijacking a user. The main reason I created this was to remove unnecessary urls. 
For instance in my case for instance I do not have a username for my user, so the URL for hijacking via username is pointless and only clutters my URLs. The defaults stay the same so that no settings needs to be changed for existing setups, in other words this is hopefully non breaking change.

Add setting to choose which user attributes can be used for hijacking a user

---

hijack/urls.py

The problem with the old method is that it does not support
- Internationalized TLDs, domains or users, such as .xn--4gbrim domains
- Geographic TLDs, such as .europe
- ICANN-era TLDs, such as .audio and .clothing
The new regex still matches <anything>@<anything>.<anything> so we still have some mail
characteristics in the URL.

Use a more liberal/naive approach to regex checking for an email

---

hijack/admin.py

when using login with id it tries to get obj.id (object is the User object).
However not all user models have an id available. 
Later on it searches for the user using the PK. So this change is fine for people who use id as a reference since it should be the same as PK.

fixed login with id when obj has no id attribute

---

README.md
hijack/helpers.py
hijack/tests/hijack_tests.py

Added ALLOW_STAFF_TO_HIJACK_STAFF_USER setting, added tests and created a separate function for the permission check.
Keep in mind that the permission check is more strict now. If you want to allow staff members to hijack other staff members you need to add this setting explicitly.

PR for issue #50: Added ALLOW_STAFF_TO_HIJACK_STAFF_USER setting

---

hijack/admin.py

If username contains HTML tags, it will be rendered without escaping. Classic XSS vulnerability.

fix security vulnerability in admin

---

hijack/admin.py

In a Python 2 environment, the format string isn't unicode and so it can cause a UnicodeEncodeError if the user's display name contains unicode characters (for example: Luis García).

Unicode in user name when generating hijack URL

---

README.md
hijack/helpers.py
hijack/middleware.py

Fix of Incompatibility if used several user backends and RemoteUserMiddleware
To use place
`'hijack.middleware.HijackRemoteUserMiddleware',`
between of `django.contrib.auth.middleware.AuthenticationMiddleware` and `django.contrib.auth.middleware.RemoteUserMiddleware` in `settings.MIDDLEWARE_CLASSES`

PR for issue #72. Hijack with RemoteUser

---

hijack/templates/hijack/notifications.html

The current hide button does not work when there is a path prefix because it uses 'request.path'.  Replacing this with 'request.path_info to get proper full path.

Fix hide button to redirects correct full path 

---

hijack/helpers.py
hijack/tests/hijack_tests.py

with the `ALLOW_STAFF_TO_HIJACK_STAFF_USER` setting set to `True` staff members were able to hijack admins if they were also staff.

Do not allow staff to hijack admins

---

hijack/helpers.py

Currently if you use the UUID field for the user primary key then while logging in you get the traceback
UUID('85410f5f-ec82-4148-ba78-5be5a79f0fb1') is not JSON serializable
This happens because:
https://github.com/arteria/django-hijack/blob/master/hijack/helpers.py#L117
Once the session serializer finds a UUID field it fails.
The problem is also described here:
https://code.djangoproject.com/ticket/24161
The fix is also from Djangos current code:
https://github.com/timgraham/django/blob/0f7f5bc9e7a94ab91c2b3db29ef7cf000eff593f/django/contrib/auth/__init__.py#L111

fix UUID serialization issue at login_user

---

hijack/middleware.py

just because the HijackRemoteUserMiddleware don't have the authenticate method.

FIX Error authenticate method not defined

---

hijack/urls.py

django-guardian needs a anonymous user, which has a user-id of -1 in the suggested default config:
> https://github.com/django-guardian/django-guardian#configuration
This patch adjusts the regex in the urls.py to allow for this negative userid. Without this patch rendering the userlist in the admin fails.

Changed regex for userid to allow negative IDs

---

hijack/helpers.py

Django-hijack fails when your User table does not uses the column `id` as the primary key.

Use pk to access the User primary key

---

hijack/helpers.py

Not all user models have "id" as their primary key. Django's pk value handles this more elegantly. This is already being done on line 114 and 127.

Using Django's PK for hijacked

---

setup.py

We had to do export `LC_ALL=env_US.utf8` to get things working, this fixes that.
```
Collecting django-hijack==2.0.2 (from -r requirements/common.txt (line 29))
Downloading django-hijack-2.0.2.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-lph62f8b/django-hijack/setup.py", line 47, in <module>
long_description=read('README.md'),
File "/tmp/pip-build-lph62f8b/django-hijack/setup.py", line 39, in read
return open(os.path.join(os.path.dirname(__file__), fname)).read()
File "/home/sendcloud/releases/master/virtualenv/3.4_5c623d701cdd1926bc2bcc4753d85a9e/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' …
```

UnicodeDecodeError during pip install

---

hijack/admin.py

render function already assumes dict will be converted to context in Django 1.10. #104

Not passing context to render

---

hijack/admin.py

This fixes the error message about form plural
ValueError: plural forms expression could be dangerous

Changed the ugettext to ugettext_lazy

---

docs/configuration.md
hijack/admin.py
hijack/settings.py

When intergrating with non-standard django-admin skins (I'm using django-suit specifically) it would be nice to able to customize the  #button template without having to rewrite the `HijackUserAdminMixin `entirely.
The easiest way that I see is to make the location of `button_template `into a setting - which defaults to what the current default is.

Make button_template in to a setting

---

hijack/helpers.py

The previous code would have kept any session keys appearing after the line triggering `KeyError`. This code drops all session keys regardless if they were set.

Fix end-of-hijack session cleanup code

---

hijack/templatetags/hijack_tags.py

When there is another syntax or parsing error in the django template, the original stack trace is hidden because django hijack then crashes when rendering the template tag with "KeyError: 'request'" on that line.
It’s particularly annoying when running unit tests, so making this a bit more exception safe.

Avoid "KeyError: 'request'" when other templates error

---

hijack/templatetags/hijack_tags.py

Following #119, it turns out the `all` statement called shortly after is now crashing, as it's evaluating all the statements (rather than stopping at the first False one), and therefore raising a "NoneType has no attribute session" when `request` is `None`.
It prevents us from serving the [custom 500 handler](https://docs.djangoproject.com/en/1.9/topics/http/views/#customizing-error-views) from Django, because our 500.html inherits from our base template which has the hijack template tag. Not sure if this was a known limitation, but this is new PR is fixing it.

Avoid server error when rendering handler500

---

docs/index.md
hijack/templatetags/hijack_tags.py
hijack/tests/test_app/templates/hello.html
hijack/tests/test_hijack.py

I found myself wanting to display/hide elements on the page that were not just the hijack notification. This simple template filter checks the session to see if the request is hijacked.
Ex: You might not want to muck up your google analytics data with requests that aren't from the actual user.
```html
{% load hijack_tags %}
{% if not request|is_hijacked %}
<script src="/js/google-analytics.js"></script>
{% endif %}
```

Added a generic template filter to see if request is hijacked

---

README.md

This is useful to be able to quickly check these things:
- Whether this package has been released on PyPI or not
- Which version number is the latest on PyPI
- Once you click on the link, you can verify what the PyPI package name is, for use with `pip`

Add link and badge to PyPI

---

hijack/static/hijack/hijack-styles.css
hijack/templates/hijack/notifications.html

My content was hidden by the notification bar.
So I quickly assembled a fixed to "push" the masked content by 50px :
- added a "hijacked-warning-wrapper" div
- added some css properties.
Before:
After:
I Know there's a hide button, though it reloads the page, and I will remove this button on my project anyway.

mini-css-fix: avoid content to be hidden by the fixed notification warning.

---

hijack/helpers.py
hijack/tests/test_hijack.py

Don't update hijacker/hijacked last login; fixes 5d6e69e for Django ≥2.0

---

hijack/middleware.py

In Django 2.0, support for user.is_authenticated() was removed in favor of the user.is_authenticated property that was introduced in Django 1.10 (https://code.djangoproject.com/ticket/25847)
This results in a 'bool' object is not callable error when using HijackRemoteUserMiddleware.
I'm not entirely sure this is the absolute best fix for the issue, but I thought it couldn't hurt to try to offer a solution while bringing up the issue.

add conditional to use is_authenticated property when django >= 1.10

---

hijack/helpers.py
hijack/signals.py
hijack/tests/test_hijack.py

I'm not sure why the signals are transporting the user *IDs* only, but it's quite a shame because it requires making new database requests within the signal receiver(s).
This PR adds the full user instances in signal parameters, while keeping the IDs for backward compatibility. Note that the argument order was unchanged so **old code will not break** with this patch.

signals: send both the user instances and user IDs for bw compatibility

---

hijack/templatetags/hijack_tags.py

1. `_render_hijack_notification` comes with `template_name` as an new keyword argument.
2. Jinja support: A new filter named `jinja_hijack_notification` was introduced. It takes a request and an optional template_name.

Jinja support and modified _render_hijack_notification.

---

CHANGELOG.txt
hijack/helpers.py
tox.ini

Hello,
As mentioned in #173, Django 2.1 now requires allowed_hosts when calling the internal django util `http.is_safe_url`. I set it to `{request.get_host()}`, as that's how I observed a few other libraries and the django test suite using it. This change affects all Django versions >= 1.11, as that was the first version to accept the allowed_hosts parameter.
I don't think any new tests need to be written for this, but maybe a new HIJACK_REDIRECT_HOSTS setting could be added for customizing it, if someone wants that.
Thanks,
Phillip Marshall

Fixed Django 2.1 compatibility

---

.github/workflows/release.yml

To create a new release a user would simply create a new GitHub release. This can be done by any repo member with write access.
This workflow could be further enhanced using `setuptools-scm`, to derive the PyPi version number from Git tags and commits.

Add semi-automatic release workflow

---

docs/index.md

I've added an examples to the documentation on how to use properly reversed urls instead of hardcoding Django and hijack urls. Hardcoded urls are bad for several reasons. For example, on multi-language sites hardcoded urls would result in constant switch to the default language when hijacking the user and releasing hijack which is extremely annoying behaviour.

Avoid usage of the hardcoded urls.

---

.github/workflows/ci.yml

Added a matrix for lint action
Added caching for packages from requirements.txt
This way the code looks much more compact and we don't repeat the same actions.
I also got rid of `cat` from requirements.txt and install all dependencies at once. No need to worry as they are now cached.

Use matrix for lint

---

docs/configuration.md
hijack/checks.py
hijack/settings.py
hijack/templates/hijack/notifications.html
hijack/templates/hijack/notifications_bootstrap.html
hijack/tests/test_checks.py
hijack/tests/test_hijack.py
hijack/tests/test_urls.py
hijack/tests/test_views.py
hijack/urls.py
hijack/views.py

Simplify URL and view structure. Add support for multiple PK types
based on URL pattern as well as natural key support via URL patterns.
Changes:
* Deprecate `HIJACK_URL_ALLOWED_ATTRIBUTES` setting favoring `HIJACK_USER_URL_PATTERN`.
* Deprecate URL names `login_with_id`, `login_with_username` and `login_with_email` favoring `acquire`.
* Deprecate URL name `release_hijack` favoring `release`.
* Deprecate views `login_with_id`, `login_with_username` and `login_with_email` favoring `release_user_view`.
* Deprecate view `release_hijack` favoring `release_user_view`.
Close #196
Close #183
Close #184
Close #198
Close #147
Close #175

Add support for non-integer primary key user models

---

docs/index.md

`{% load staticfiles %}` has been deprecated since Django 1.10.
Changed to current `{% load static %}`.

Docs: fix load static

---

hijack/static/hijack/hijack.scss

In Django admin the button has a background color, which I didn't notice before, see here:
I removed it, so the buttons look flat as they should.

Fix notification button appearance in Django admin

---

hijack/static/hijack/hijack.scss

The block overlapped and prevented clicking on elements

Fix block overlay

---

README.md

References #317 
This provides new users with information on the 3.x rewrite - to find the latest documentation in the docs folder and that the RTD site is only for the 2.x version which is API incompatible.

Add README information on 3.x docs

---

hijack/locale/de/LC_MESSAGES/django.po

As explained in issue [issue 335](https://github.com/django-hijack/django-hijack/issues/335) this are the corrected translation.
I used mainly the translation of the former django-hijack-admin package to come up with the suggested changes.

Add correct german translations for DjangoAdmin integration

---

hijack/locale/es/LC_MESSAGES/django.po

Fixed unfortunate translation from "secuestrar" (kidnap) to "suplantar" (supplant, closer to the intended hijack meaning).

Updated Spanish translation

---

docs/customization.md
hijack/permissions.py
hijack/tests/test_permissions.py

Hijacking inactive users (i.e. users with `is_active=False`) is not allowed to prevent
dead locks, since an inactive user cannot be released.

Fix #369 -- Do not allow inactive users to be hijacked

---

hijack/middleware.py
hijack/tests/test_middleware.py

Django's session middleware sets the vary on cookie header if
the session has been accessed by the request or any other
middleware. Therefore, we need to avoid loading the session
of the session is empty and there is not user, nor any hijacked
user for that matter.

Do not touch empty sessions to avoid vary on cookie header

---

hijack/middleware.py
hijack/tests/test_middleware.py

Follow up on #407 - `process_response` is affected in a similar way.
In order to decide on notification rendering, library checks `request.user.is_hijacked`, which accesses the session. We can skip that part when the session is empty.

Ignore hijacking logic in response processing in case of empty session

---

docs/customization.md

There is a small typo in docs/customization.md.
Should read `recommended` rather than `recommened`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, recommened -> recommended

---

hijack/contrib/admin/admin.py
hijack/middleware.py
hijack/tests/test_middleware.py

Render both the admin button and the middleware notification template
using a `RequestContext` instead of a `RenderContext`. This will
cause the CSRF token to be injected automatically into the context
for the notitication. Futhermore, users are able to inject their
own context, via context processors, to futher customize their
templates.

Resolve #504 -- Use a RequestContext to render templates

---

hijack/middleware.py
hijack/tests/test_middleware.py

If the session wasn't accessed we do not need to modify the response.
Session get accessed lazily if someone accesses request.user or
request.session. In those cases Django will add cookie to the
Vary-On HTTP header. This will prevent browsers from caching the
results.
Furthermore, accessing the user when not needed will cause unwanted
IO on request, that don't need authentication or vary content based
on users.
We use the same behavior Django implements in the authentication
middlware, where a user is a lazy object and will only be fetched
if needed. We simply overwrite the user and add another setup
hook.

Do not access the session unless needed

---

setup.cfg
setup.py

Setuptools doesn't create empty folders anymore. Therefore, we need to manually create the folders before compiling the MO files using gettext.

Fix setup script and CI

---

hijack/locale/nl/LC_MESSAGES/django.po

The previous translations were a bit weird in the context they are used.

Update Dutch translations

---

hijack/tests/test_views.py
hijack/views.py

If the user is not authenticated, `LockUserTableMixin.dispatch` raises `User.DoesNotExist`. This started happening after https://github.com/django-hijack/django-hijack/commit/a36fbb8fa71206ad01d330e9f34bb321d5340f82:
https://github.com/django-hijack/django-hijack/blob/a36fbb8fa71206ad01d330e9f34bb321d5340f82/hijack/views.py#L67
To address it, I changed the parent classes order so `LoginRequiredMixin` does its job first.

Ref #613  -- Handle unauthenticated users in hijack views

---

.github/workflows/ci.yml
CONTRIBUTING.md
setup.cfg

Add Python 3.12 official support:
- Added to CI (I had to tweak the github action matrix according to the [Django supported versions](https://docs.djangoproject.com/en/4.2/faq/install/#what-python-version-can-i-use-with-django) documentation.
)
- Updated pypi classifiers
- Updated "pytest" command in CONTRIBUTING.md

Add official Python 3.12 support

---

.github/workflows/ci.yml
CONTRIBUTING.md
hijack/tests/test_app/settings.py
setup.cfg

Built on top of #627, Add support for the new Django 5.0 version
- Added to the CI.
- Updated pypi classifiers
Awareness:
- The [PickleSerializer](https://docs.djangoproject.com/en/4.2/topics/http/sessions/#django.contrib.sessions.serializers.PickleSerializer) used in the tests is deprecated since Django 4.1 and is removed in Django5. But the Json alternative can't serialize datetimes with Django 3.2. Considering the remaining lifetime of Django 3.2 I let it use the old Serializer.
Thanks a lot for maintaining this lib!

Add official Django 5.0 support

---

.github/workflows/ci.yml
setup.cfg

Django 4.1 reached the end of life on December 1. 2023.

Drop official Django 4.1 support

---

hijack/tests/conftest.py
hijack/tests/test_app/routers.py
hijack/tests/test_app/settings.py
hijack/tests/test_views.py
hijack/views.py

Hello,
The `transaction.atomic` call to lock the User table currently always happens against the default DB. This is because `transaction.atomic` has no knowledge of which databases will be queried in a multi database scenario (since the queried database is determined dynamically by the database router being used).
This PR updates the flow to fetch the database that is used for writing to the User model, and ensures a lock is placed against that specific database.
Happy to get feedback on the fix and the test. Thanks!

Ensure transaction.atomic is against the db with the User model.

---

hijack/locale/cs/LC_MESSAGES/django.po

The previous translation was like "Release" - as you can see, my is the same as for the other `impersonate`'s

Fix Czech translation for "impersonate"

---

docs/customization.md

Hi everyone! I've stumbled upon the same problem of this #711 when customizing the redirect url in django-hijack, I've seen that since July nobody opened a pr so I did it myself. I've copy/pasted the actual template (because also `static` and `i18n` templatetags library were missing, not a big problem but I think this way if a user copy/paste from the docs everything should work as expected.

Fix notification layout documentation example template

---

hijack/static/hijack/hijack.js
tests/__tests__/hijack.test.js

The fetch-based integration ignored the redirect provided by the backend. This may prohibit user input sanitation. It's not severe but unexpected. This patch amends a form element to the body to utilize the native form submission.

Fix #769 -- Use native form submission in Django admin
