django-hijack/django-hijack

README.md
hijack/helpers.py

If set, redirect to the "next" request.GET attribute
or the django-hijack specific settings attribute or
the LOGIN_REDIRECT_URL.

adapt the hijack and releace processes

---

.gitignore
README.md
setup.py

update readme & setup.py

---

hijack/admin.py
hijack/tests/hijack_tests.py
hijack/urls.py
test_requirements.txt

fixes #35
Also updated reverse on UserAdmin list display hijack_field to use newly named URL.

Adding names to unamed urls + tests

---

hijack/admin.py

fix admin hijack_field to use proper user attributes setting values

---

hijack/__init__.py
hijack/admin.py
hijack/helpers.py
hijack/templatetags/hijack_tags.py
hijack/tests/hijack_tests.py
hijack/tests/manage_settings.py
hijack/tests/south_settings.py
hijack/tests/test_app/urls.py
hijack/tests/test_app/views.py
hijack/tests/test_settings.py
hijack/tests/urls.py
hijack/urls.py
hijack/views.py
manage.py
runtests.py
setup.py

PR for #58:
I fixed nearly all pep8 and flake8 errors. There is only one flake8 error open in `tests/manage_settings.py`  , but this one can't be fixed without changing the way how the code works.

PR for #58: fixed pep8 and flake8 errors

---

AUTHORS
hijack/admin.py
setup.py

Support for django 1.4 - 1.8
pull for #65

Security update from alexallah with django-compat support

---

hijack/helpers.py
hijack/views.py
setup.py

Rpkilby patch

---

hijack/helpers.py

A quick fix for @NotSqrt's issue #56.
`resolve_url` is fairly straight forward, so it should be safe to merge.

Used `resolve_url` to properly handle URL redirect

---

hijack/helpers.py

Instead of relying on a hack that saves then restores `user.last_login`<sup>[1](#fn1)</sup>, we disconnect `update_last_login` on the `user_logged_in` signal before login, then restore it if needed.
The related test still passes, and as added value we don't have to `save()` the user nor deal with an attribute that may not exist at all.
I also renamed `user` to `hijacked`, because it was done this way in other functions and prevents any confusion between hijacker and hijacked.
--
<a name="fn1">[1]</a> This attribute may not exist on custom `User` models and triggers an expensive database update.

Don't save hijacked user at login; disconnect update_last_login instead

---

hijack/locale/cs/LC_MESSAGES/django.po

In this PR I added Czech translations of all translable strings

Czech localization

---

docs/index.md

I Copy-Pasted the Signals example from the docs and ran into:
```
ValueError: Signal receivers must accept keyword arguments (**kwargs).
```

Update Signals Example in Docs

---

hijack/locale/fr/LC_MESSAGES/django.po

* missing accent
* the French version of "currently working on behalf of" string transported the wrong meaning

locale: fix French strings

---

README.md

Removing broken badges, add image availability from pypi

Readme small improvements

---

hijack/helpers.py
hijack/middleware.py
hijack/signals.py
hijack/tests/test_app/urls.py
hijack/tests/test_hijack.py
hijack/tests/urls.py
hijack/urls.py
setup.cfg

I changed the pytest config to fail on warnings to detect deprecation early. Next I went ahead and address each deprecation warning in a separate commit.

Resolve all open deprecation warnings

---

requirements.txt

To appease my inner perfectionist, I really need to sort this file

Small sorting of requirements.txt file

---

hijack/templates/hijack/notification.html

I added a block so that you can easily extend the template when needed and use super situationally.
```
{% extends ... %}
{% block content %}
{%if ......%}
{{ block.super }}
{% else %}
custom
{% endif %}
{% endblock content %}
```

Add block in notification.html

---

hijack/locale/fr/LC_MESSAGES/django.po

Hi,
Just a small correction on the french translation.
Thank you.

fix(locale): correction on the french translation

---

.github/FUNDING.yml
README.md

Move funding links GitHub sponsorships

---

docs/index.md

A few minor spacing and spelling/grammatical fixes.

Fix typos and spacing

---

docs/customization.md

docs: fix security typo

---

.github/workflows/ci.yml
.github/workflows/release.yml

- Pin actions to major version only to reduce dependabot PRs
- Add Python version to all python actions

Fix CI suite version issues

---

.github/workflows/ci.yml
setup.cfg

Add official Django 4.1 version support

Add Django 4.1 support

---

docs/customization.md

Looking at past issues like [this one](https://github.com/django-hijack/django-hijack/pull/392), or [this other one](https://github.com/django-hijack/django-hijack/issues/391), it looks like this is a frequent question.

docs: explain how to customize admin hijack button

---

hijack/views.py

Fix #367 -- Add fallback if LOGOUT_REDIRECT_URL is None

---

hijack/locale/ja/LC_MESSAGES/django.po

Hi all, I have made the Japanese localisation change in this PR.
Please review the changes. :pray: 
```
$ cd /your/path/django-hijack
$ django-admin makemessages -l ja -e html -e py
```

Add Japanese language translation

---

docs/index.md

Typo on line 86 explaining how to add hijack.contrib.admin to the installed apps.

Typo on index.md

---

hijack/tests/test_views.py
hijack/views.py

Fixed: Performance degraded after upgrade to 3.4.1

---

CONTRIBUTING.md
hijack/__init__.py
hijack/contrib/admin/__init__.py
hijack/views.py
setup.cfg

Cleanup code for unsupported Django versions ( <3.2 )

Cleanup code for unsupported Django versions

---

hijack/static/hijack/hijack.js
tests/__tests__/hijack.test.js

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

Use globalThis in favor of window or global

---

hijack/static/hijack/hijack.js
tests/__tests__/hijack.test.js

Fix  #744 --  Use event.currentTarget in admin JS

---

.github/workflows/ci.yml
pyproject.toml
tests/test_views.py

* Add Python 3.13
* Drop Python 3.8
* Add Django 5.1

Update Python and Django version support

---

hijack/static/hijack/hijack.css

@codingjoe Dark mode is currently broken. 
**Before:**
**After:**

Fix dark mode

---

hijack/locale/ru/LC_MESSAGES/django.po

Hi, I corrected the translation a little

Update ru django.po
